### ISSUE TITLE
No Settings Tab

### ISSUE THREAD

**Issue by conneroisu** [lukasbach/obsidian-code-files#1]
**Describe the bug**
After cloning the repository and building the plugin, I was able to load the plugin into obsidian. The settings tab is not loading into the app.
**To Reproduce**
Steps to reproduce the behavior (ideally a codesandbox link or similar if for a library issue):
To reproduce, I would clone the repository into a new vault and ensure that the settings tab for the plugin loads. 
**Expected behavior**
The plugin should have a settings tab. The repository even includes this settings tab in src, but needs to load correctly. 

**Additional context**
Windows 11

**Comment by lukasbach** [comment]
Hey, thanks for your report! It worked for me with no problems. Assuming that you build the plugin and added the plugin's manifest and JS file so that it comes up in your plugin list, I assume that the plugin runs into an error when loading up. Can you open your devtools (CTRL+i) and share the logs displayed in the console tab there? There should probably be an error in there related to the plugin. Thanks!

**Comment by conneroisu** [comment]
Sorry for the quick reply but I am in heavy midterms right now
here you go
[cid:d6a0fea4-a2fe-44a0-8bc1-876aab4e2be2]
________________________________

**Comment by lukasbach** [comment]
Hey @conneroisu, it looks like your attachement did not went though to github, it just shows an identifier string. Can you share the attachement on github directly, or send the log to contact@lukasbach.com please?

Thank you, and good luck on your midterms!

**Comment by volond1975** [comment]
Add Import/ Export from/to code bloc Obsidian Note

**Comment by EvilDragonFly** [comment]
![image](https://github.com/lukasbach/obsidian-code-files/assets/48235622/037a92c4-bd38-4027-881c-ebad807533a2)
no setting options

**Comment by conneroisu** [comment]
This issue seems to be fixed and the plugin works!
